# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160503_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='perferred_name',
            new_name='preferred_name',
        ),
    ]
