# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('length', models.DurationField()),
                ('date_uploaded', models.DateTimeField()),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('file_location', models.URLField()),
                ('contributor', models.ManyToManyField(related_name='contributor_user', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
