# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentary',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='length',
            field=models.DurationField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='likes',
            field=models.ManyToManyField(blank=True, default=[], related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='location',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='state',
            field=models.CharField(blank=True, default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
